In [99]:
import duckdb
import json
df = duckdb.query("""
SELECT repo, 
    block_type, 
    -- Extract specific fields from JSON
    json(raw_json)->'$."$type"' as type,
    json(raw_json)->'$.createdAt' as created_at,
    json(raw_json)->'$.text' as text,
    json(raw_json)->'$.langs' as langs,
    -- Extract nested embed
    json(raw_json)->'$.embed."$type"' as embed_type,
    json(raw_json)->'$.embed.record.cid' as embed_cid,
    json(raw_json)->'$.embed.record.uri' as embed_uri,
    json(raw_json) AS full_data,
FROM '../output/blocks/year=2026/month=6/day=8/*.parquet'
WHERE block_type = 'app.bsky.feed.post'
""").df()

In [101]:
import duckdb
import json
df = duckdb.query("""
SELECT repo, 
    block_type, 
    json(raw_json) AS full_data,
FROM '../output/blocks/year=2026/month=6/day=8/*.parquet'
""").df()

In [105]:
df[df['block_type'] == 'app.bsky.graph.unfollow']["full_data"].loc[927491]

'{"$type":"app.bsky.graph.unfollow","createdAt":"2026-06-08T12:00:42.576+02:00","subject":"did:plc:tiksgdhasw7l3qz4nvfeiusb"}'

In [112]:
import duckdb
import json
df = duckdb.query("""
SELECT block_type, 
    COUNT(*) AS count, 
FROM '../output/blocks/year=2026/month=6/day=8/*.parquet'
GROUP BY block_type
ORDER BY count DESC
""").df()

In [115]:
df.head(n=10)

                 block_type    count
0                    facets  1893173
1        app.bsky.feed.like   131276
2        app.bsky.feed.post    28579
3      app.bsky.feed.repost    19483
4     app.bsky.graph.follow    11271
5        app.studynext.task     2552
6      app.bsky.graph.block     2432
7  app.bsky.feed.threadgate     1541
8    app.bsky.feed.postgate      934
9    app.bsky.actor.profile      844

In [118]:
df = duckdb.query("""
SELECT *, json(ops) as decoded_ops
FROM '../output/commit/year=2026/month=6/day=8/*.parquet'
LIMIT 100
""").df()

In [122]:
df

,commit_cid,repo,rev,seq,prev_cid,time,too_big,ops_count,ops,blob_cids,day,month,year,decoded_ops
0,bafyreigemdvxcwqj2il7ehdpf2wf2j3bnit6duk3rpjof...,did:plc:nxhtdhtrulwx7drozx3zpnsb,3mnrfj7irpl23,30739341088,bafyreiaaf4r7zjwtx7wqxdz7sfg4jgefb6a323qo6kizk...,2026-06-08T09:45:19.558Z,False,1,"[{""action"":""create"",""cid"":""bafyreidim2gdcsywt2...",[],8,6,2026,"[{""action"":""create"",""cid"":""bafyreidim2gdcsywt2..."
1,bafyreiay6fbxhjpyqe3eqjsxcuyuegdbbt4vimnuoaw5l...,did:plc:klgsngu3stfdjmhmekxb37f5,3mnrfj7cnyx2q,30739341089,bafyreieotdcwplsbiu6aswkn2k2arqdopuqrnm4l2uxgx...,2026-06-08T09:45:19.358Z,False,1,"[{""action"":""create"",""cid"":""bafyreiepdhppvlx4us...",[],8,6,2026,"[{""action"":""create"",""cid"":""bafyreiepdhppvlx4us..."
2,bafyreigkk2ph7wwqnsvusr2j26tvxruhhgroiu24t6h46...,did:plc:xpvkf37moi3jikts77vlka5o,3mnrfj7hu7f2c,30739341090,bafyreicpivsqij46dm7dusxaqtvatzi6dus3qmsmkr73v...,2026-06-08T09:45:19.528Z,False,1,"[{""action"":""create"",""cid"":""bafyreidwt7dbwbwwdp...",[],8,6,2026,"[{""action"":""create"",""cid"":""bafyreidwt7dbwbwwdp..."
3,bafyreig66yr5ri663nfb4qwa6uemec5h2z6vwia3thwkl...,did:plc:x2fi2x5v2jnhyuqlyub4y4y2,3mnrfj7jzr52u,30739341091,bafyreichivzuligbhcynamgkt6aun5l6ftujuafe6c5t7...,2026-06-08T09:45:19.597Z,False,1,"[{""action"":""create"",""cid"":""bafyreiazm4acrltf7b...",[],8,6,2026,"[{""action"":""create"",""cid"":""bafyreiazm4acrltf7b..."
4,bafyreifged72xn6w7y7dv5pdiqyqddvutf5vabfyz5iip...,did:plc:sp5ndxed7mf3vlie3rneslyf,3mnrfj73ufu2p,30739341092,bafyreihpec2kkdheye2xxmqi7rvfonx3dcpoxojx376bj...,2026-06-08T09:45:19.136Z,False,1,"[{""action"":""delete"",""cid"":null,""path"":""app.bsk...",[],8,6,2026,"[{""action"":""delete"",""cid"":null,""path"":""app.bsk..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,bafyreidic46ii5hhvm7gq64dkq4sc3j6rfaj5lb4gb7ul...,did:plc:ofiie5xoodzuw36udy2nqjuz,3mnrfj7wsrw2l,30739341183,bafyreigcxply3g7c2fmy7gb73ozl6p4ojowgor2uziu3h...,2026-06-08T09:45:20.017Z,False,1,"[{""action"":""create"",""cid"":""bafyreiare4tcvlhib4...",[],8,6,2026,"[{""action"":""create"",""cid"":""bafyreiare4tcvlhib4..."
96,bafyreign2x7ycpyhu5h5s2xey4bjrpw2y7hoczra4cw5j...,did:plc:pqjel6qcdq7uuq7qjugfgi6z,3mnrfj6sp4x2q,30739341184,bafyreib2qzzq5kmqsu6scxjfxffhoh4vj4osqvqf6yw7t...,2026-06-08T09:45:19.782Z,False,2,"[{""action"":""create"",""cid"":""bafyreifczjwsfwxryi...",[],8,6,2026,"[{""action"":""create"",""cid"":""bafyreifczjwsfwxryi..."
97,bafyreie5b74q3ju3uubo7lsq3nkpycrz2n4fl7bt7k2xf...,did:plc:rnepcirvlsclb5pnzlcnkd5l,3mnrfj77iqh2l,30739341185,bafyreigk5ltoftherzum4pivjbr44p4jucvufddkdps7q...,2026-06-08T09:45:19.253Z,False,1,"[{""action"":""create"",""cid"":""bafyreideoidutorgfy...",[],8,6,2026,"[{""action"":""create"",""cid"":""bafyreideoidutorgfy..."
98,bafyreigujougroomgmnikjzsef2qpyx3t4z7x4d3lnrdv...,did:plc:ccy6dpzkw6q3kv6qrcyubpnp,3mnrfj7u4rx2r,30739341186,bafyreida3te5kvhpkn5vly3eaetf6isejiolwf6lab34b...,2026-06-08T09:45:19.931Z,False,1,"[{""action"":""create"",""cid"":""bafyreihtjfhmyeci53...",[],8,6,2026,"[{""action"":""create"",""cid"":""bafyreihtjfhmyeci53..."
99,bafyreibvyo4vexvpwwlfscjmycbj22ntpqxqb5zwlwklh...,did:plc:vvdwd7ztegoylkoopqepu7vh,3mnrfj7oqxo26,30739341187,bafyreifb2fwvrhg7akr2c5dbegqqudki7mwucdbxaqn7p...,2026-06-08T09:45:19.754Z,False,1,"[{""action"":""create"",""cid"":""bafyreid4hpniwzhymk...",[],8,6,2026,"[{""action"":""create"",""cid"":""bafyreid4hpniwzhymk..."

In [123]:
df["decoded_ops"].loc[96]

'[{"action":"create","cid":"bafyreifczjwsfwxryic6fbqmcnnt5fxs5qhzwqjew2hc6g77ipzdfw2gze","path":"app.bsky.feed.post/3mnrfj7fsrc2t","record_type":"app.bsky.feed.post"},{"action":"create","cid":"bafyreicf5n6mdgmbtaeh4aojnsd3ayrhrcp2mjo22mzvogkp6qxxkebgj4","path":"app.bsky.feed.threadgate/3mnrfj7fsrc2t","record_type":"app.bsky.feed.threadgate"}]'